version: '3'
services:
  web:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - /usr/app/node_modules
      - //docker/frontend:/usr/app
  test:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/app/node_modules
      - //docker/frontend:/usr/app
    command: ["npm", "run", "test"]